export const actionTypes = {
  // AUTH ACTIONS ...

  // ACTIONS RELETED TO SINGUP AUTHENTICATION ...
  AUTH_SIGNUP_START: "AUTH_SIGNUP_START",
  AUTH_SIGNUP_SUCCESS: "AUTH_SIGNUP_SUCCESS",
  AUTH_SIGNUP_FAIL: "AUTH_SIGNUP_FAIL",

  // ACTIONS RELETED TO LOGIN AUTHENTICATION ...
  AUTH_LOGIN_START: "AUTH_LOGIN_START",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAIL: "AUTH_LOGIN_FAIL",

  // ACTIONS RELETED TO THEE LOGOUT...
  AUTH_LOGOUT_START: "AUTH_LOGOUT_START",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
  AUTH_LOGOUT_FAIL: "AUTH_LOGOUT_FAIL",

  // ACTIONS RELETED TO THE RESET PASSWORD...
  AUTH_RESET_PASSWORD_START: "AUTH_RESET_PASSWORD_START",
  AUTH_RESET_PASSWORD_SUCCESS: "AUTH_RESET_PASSWORD_SUCCESS",
  AUTH_RESET_PASSWORD_FAIL: "AUTH_RESET_PASSWORD_FAIL",

  // ACTIONS RELETED TO THE NEW PASSWORD...
  AUTH_NEW_PASSWORD_START: "AUTH_NEW_PASSWORD_START",
  AUTH_NEW_PASSWORD_SUCCESS: "AUTH_NEW_PASSWORD_SUCCESS",
  AUTH_NEW_PASSWORD_FAIL: "AUTH_NEW_PASSWORD_FAIL",

  // AUTH SOME THING WENT WRONG ...
  AUTH_SOMETHING_WENT_WRONG: "AUTH_SOMETHING_WENT_WRONG",
  AUTH_SOMETHING_WENT_WRONG_CLOSE: "AUTH_SOMETHING_WENT_WRONG_CLOSE",

  CLEAR_AUTH_SIGNUP_ERRORS: "CLEAR_AUTH_SIGNUP_ERRORS",
  CLEAR_AUTH_LOGIN_ERRORS: "CLEAR_AUTH_LOGIN_ERRORS"
};
